title: "Will Townes"
description: "research profile and technical blog"
url: "http://localhost:4000"
paginate: 10
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title/
comments: true
plugins: [jekyll-paginate,jekyll-sitemap]
markdown: kramdown
